from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd


SCRIPT_PATH = Path(__file__).resolve()
BASELINE_ROOT = SCRIPT_PATH.parents[1]
PROJECT_ROOT = BASELINE_ROOT.parents[1]

sys.path.insert(0, str(BASELINE_ROOT))

from utils.io_utils import ensure_dir, read_csv_safe, save_json, make_safe_name
from utils.geometry_features import angle_degrees


# ======================================================================================
from utils.geometry_features import angle_degrees


# ======================================================================================
# FILE 03: COMPUTE GUIDED GEOMETRIC AND KINEMATIC FEATURES
# ======================================================================================
#
# Original Yadav et al. pipeline:
#   3D skeleton coordinates
#   -> geometric and kinematic feature calculation
#   -> raw skeleton coordinates + derived guided features
#
# Paper-style derived features from Table 2:
#   1. Velocity in X direction
#   2. Velocity in Y direction
#   3. Velocity in Z direction
#   4. Distance from the floor
#   5. Angle Left Standing
#   6. Acceleration in X direction
#   7. Acceleration in Y direction
#   8. Acceleration in Z direction
#   9. Height
#   10. Angle Standing
#   11. Angle Sitting Left
#   12. Angle Sitting Right
#   13. Angle Standing Right
#   14. Width
#
# Adapted project:
#   We use the adapted Yadav17 skeleton generated by file 02.
#   The skeleton columns x0,y0,z0...x16,y16,z16 are already in Yadav-style order.
#
# Joint order from file 02:
#   0  hip_right
#   1  foot_left_proxy
#   2  knee_right
#   3  knee_left
#   4  hip_left
#   5  foot_right_proxy
#   6  ankle_right
#   7  ankle_left
#   8  head
#   9  spine_mid
#   10 spine_base
#   11 wrist_left
#   12 shoulder_right
#   13 shoulder_left
#   14 elbow_left
#   15 wrist_right
#   16 elbow_right
#
# Output:
#   data/guided_features/Fall/*.csv
#   data/guided_features/Not_Fall/*.csv
#   data/guided_features/guided_features_index.csv
#   outputs/reports/03_compute_guided_features_report.json
# ======================================================================================


XYZ_COLS = [f"{axis}{idx}" for idx in range(17) for axis in ["x", "y", "z"]]


GUIDED_FEATURE_COLS = [
    "velocity_x",
    "velocity_y",
    "velocity_z",
    "floor_distance_proxy",
    "angle_left_standing_deg",
    "acceleration_x",
    "acceleration_y",
    "acceleration_z",
    "body_height",
    "angle_standing_deg",
    "angle_sitting_left_deg",
    "angle_sitting_right_deg",
    "angle_right_standing_deg",
    "body_width",
]


JOINT = {
    "hip_right": 0,
    "foot_left_proxy": 1,
    "knee_right": 2,
    "knee_left": 3,
    "hip_left": 4,
    "foot_right_proxy": 5,
    "ankle_right": 6,
    "ankle_left": 7,
    "head": 8,
    "spine_mid": 9,
    "spine_base": 10,
    "wrist_left": 11,
    "shoulder_right": 12,
    "shoulder_left": 13,
    "elbow_left": 14,
    "wrist_right": 15,
    "elbow_right": 16,
}


def check_required_columns(df: pd.DataFrame, path: Path) -> None:
    missing = [c for c in XYZ_COLS if c not in df.columns]

    if missing:
        raise ValueError(f"Missing skeleton columns in {path}: {missing[:10]}")


def df_to_pose(df: pd.DataFrame) -> np.ndarray:
    """
    Convert dataframe into pose array.

    Input columns:
        x0,y0,z0...x16,y16,z16

    Output:
        pose shape = (T, 17, 3)
    """
    values = df[XYZ_COLS].to_numpy(dtype=np.float32)
    pose = values.reshape(len(df), 17, 3)
    return pose


def safe_angle(a: np.ndarray, b: np.ndarray, c: np.ndarray) -> float:
    try:
        value = angle_degrees(a, b, c)

        if not np.isfinite(value):
            return 0.0

        return float(value)

    except Exception:
        return 0.0


def angle_to_vertical_deg(p1: np.ndarray, p2: np.ndarray) -> float:
    """
    Angle between body centerline and vertical direction.

    In the adapted dataset, coordinates are normalized. The y-axis is used as the
    vertical proxy. We use abs(cos) so that flipped y direction does not break the angle.

    0 degree   -> body line is close to vertical
    90 degrees -> body line is close to horizontal
    """
    v = p1 - p2
    vertical = np.array([0.0, 1.0, 0.0], dtype=np.float32)

    norm_v = np.linalg.norm(v)
    norm_vertical = np.linalg.norm(vertical)

    if norm_v < 1e-8:
        return 0.0

    cos_value = float(np.dot(v, vertical) / (norm_v * norm_vertical))
    cos_value = abs(cos_value)
    cos_value = max(-1.0, min(1.0, cos_value))

    return float(np.degrees(np.arccos(cos_value)))


def compute_velocity_and_acceleration(pose: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """
    Paper describes velocity and acceleration from skeleton movement.
    It specifically mentions displacement of the spine mid joint between frames.

    We use spine_mid as the tracked body center proxy.

    Output:
        velocity shape     = (T, 3)
        acceleration shape = (T, 3)
    """
    center = pose[:, JOINT["spine_mid"], :]  # T, 3

    velocity = np.zeros_like(center, dtype=np.float32)
    acceleration = np.zeros_like(center, dtype=np.float32)

    if len(center) > 1:
        velocity[1:] = center[1:] - center[:-1]

    if len(center) > 2:
        acceleration[1:] = velocity[1:] - velocity[:-1]

    return velocity.astype(np.float32), acceleration.astype(np.float32)


def compute_bbox_features(pose: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Compute body height, width, and floor-distance proxy per frame.

    Paper uses:
        - Height
        - Width
        - Distance from floor

    Since our estimated 3D pose has no real floor plane, floor distance is approximated by:
        abs(head_y - min_y_of_lower_body)

    lower body joints used:
        left/right foot proxies, left/right ankles, left/right knees
    """
    x = pose[:, :, 0]
    y = pose[:, :, 1]

    body_width = np.nanmax(x, axis=1) - np.nanmin(x, axis=1)
    body_height = np.nanmax(y, axis=1) - np.nanmin(y, axis=1)

    lower_joint_indices = [
        JOINT["foot_left_proxy"],
        JOINT["foot_right_proxy"],
        JOINT["ankle_left"],
        JOINT["ankle_right"],
        JOINT["knee_left"],
        JOINT["knee_right"],
    ]

    lower_y = y[:, lower_joint_indices]
    floor_y_proxy = np.nanmin(lower_y, axis=1)

    head_y = y[:, JOINT["head"]]

    floor_distance_proxy = np.abs(head_y - floor_y_proxy)

    body_width = np.nan_to_num(body_width, nan=0.0, posinf=0.0, neginf=0.0)
    body_height = np.nan_to_num(body_height, nan=0.0, posinf=0.0, neginf=0.0)
    floor_distance_proxy = np.nan_to_num(floor_distance_proxy, nan=0.0, posinf=0.0, neginf=0.0)

    return (
        body_width.astype(np.float32),
        body_height.astype(np.float32),
        floor_distance_proxy.astype(np.float32),
    )


def compute_angle_features(pose: np.ndarray) -> Dict[str, np.ndarray]:
    """
    Compute paper-style angle features.

    Adapted interpretation:
        angle_left_standing_deg:
            angle at left knee using hip-left, knee-left, ankle-left.

        angle_right_standing_deg:
            angle at right knee using hip-right, knee-right, ankle-right.

        angle_standing_deg:
            angle between body centerline and vertical axis.
            Body centerline = spine_base -> head.

        angle_sitting_left_deg:
            angle at left hip using spine_base, hip_left, knee_left.

        angle_sitting_right_deg:
            angle at right hip using spine_base, hip_right, knee_right.
    """
    n = len(pose)

    angle_left_standing = np.zeros(n, dtype=np.float32)
    angle_right_standing = np.zeros(n, dtype=np.float32)
    angle_standing = np.zeros(n, dtype=np.float32)
    angle_sitting_left = np.zeros(n, dtype=np.float32)
    angle_sitting_right = np.zeros(n, dtype=np.float32)

    for i in range(n):
        p = pose[i]

        angle_left_standing[i] = safe_angle(
            p[JOINT["hip_left"]],
            p[JOINT["knee_left"]],
            p[JOINT["ankle_left"]],
        )

        angle_right_standing[i] = safe_angle(
            p[JOINT["hip_right"]],
            p[JOINT["knee_right"]],
            p[JOINT["ankle_right"]],
        )

        angle_standing[i] = angle_to_vertical_deg(
            p[JOINT["head"]],
            p[JOINT["spine_base"]],
        )

        angle_sitting_left[i] = safe_angle(
            p[JOINT["spine_base"]],
            p[JOINT["hip_left"]],
            p[JOINT["knee_left"]],
        )

        angle_sitting_right[i] = safe_angle(
            p[JOINT["spine_base"]],
            p[JOINT["hip_right"]],
            p[JOINT["knee_right"]],
        )

    return {
        "angle_left_standing_deg": np.nan_to_num(angle_left_standing, nan=0.0, posinf=0.0, neginf=0.0),
        "angle_right_standing_deg": np.nan_to_num(angle_right_standing, nan=0.0, posinf=0.0, neginf=0.0),
        "angle_standing_deg": np.nan_to_num(angle_standing, nan=0.0, posinf=0.0, neginf=0.0),
        "angle_sitting_left_deg": np.nan_to_num(angle_sitting_left, nan=0.0, posinf=0.0, neginf=0.0),
        "angle_sitting_right_deg": np.nan_to_num(angle_sitting_right, nan=0.0, posinf=0.0, neginf=0.0),
    }


def compute_guided_features(pose: np.ndarray) -> pd.DataFrame:
    """
    Compute the 14 guided features following Table 2 of the paper.
    """
    velocity, acceleration = compute_velocity_and_acceleration(pose)
    body_width, body_height, floor_distance_proxy = compute_bbox_features(pose)
    angle_dict = compute_angle_features(pose)

    feature_data = {
        "velocity_x": velocity[:, 0],
        "velocity_y": velocity[:, 1],
        "velocity_z": velocity[:, 2],

        "floor_distance_proxy": floor_distance_proxy,

        "angle_left_standing_deg": angle_dict["angle_left_standing_deg"],

        "acceleration_x": acceleration[:, 0],
        "acceleration_y": acceleration[:, 1],
        "acceleration_z": acceleration[:, 2],

        "body_height": body_height,

        "angle_standing_deg": angle_dict["angle_standing_deg"],
        "angle_sitting_left_deg": angle_dict["angle_sitting_left_deg"],
        "angle_sitting_right_deg": angle_dict["angle_sitting_right_deg"],
        "angle_right_standing_deg": angle_dict["angle_right_standing_deg"],

        "body_width": body_width,
    }

    features_df = pd.DataFrame(feature_data)
    features_df = features_df[GUIDED_FEATURE_COLS]
    features_df = features_df.replace([np.inf, -np.inf], 0.0).fillna(0.0)

    return features_df


def process_one_csv(
    input_csv: Path,
    output_csv: Path,
    video_id: str,
    label: int,
    label_name: str,
    overwrite: bool = False,
) -> Dict:
    if output_csv.exists() and not overwrite:
        return {
            "status": "skipped_existing",
            "video_id": video_id,
            "label": int(label),
            "label_name": label_name,
            "input_csv": str(input_csv),
            "output_csv": str(output_csv),
        }

    df = read_csv_safe(input_csv)
    check_required_columns(df, input_csv)

    pose = df_to_pose(df)
    guided_df = compute_guided_features(pose)

    # Keep raw skeleton coordinates + guided features + metadata.
    out_df = df.copy()

    for col in GUIDED_FEATURE_COLS:
        out_df[col] = guided_df[col].astype(np.float32).values

    out_df["video_id"] = video_id
    out_df["label"] = int(label)
    out_df["label_name"] = label_name
    out_df["feature_source"] = "yadav17_minmax_skeleton_plus_guided_features"

    # Clean column order
    fixed_meta = [
        "video_id",
        "frame",
        "source_file",
        "label",
        "label_name",
        "action_label",
        "action_name",
        "normalization",
        "feature_source",
    ]

    existing_fixed = [c for c in fixed_meta if c in out_df.columns]
    other_cols = [
        c for c in out_df.columns
        if c not in XYZ_COLS and c not in GUIDED_FEATURE_COLS and c not in existing_fixed
    ]

    out_df = out_df[XYZ_COLS + GUIDED_FEATURE_COLS + existing_fixed + other_cols]

    ensure_dir(output_csv.parent)
    out_df.to_csv(output_csv, index=False)

    feature_stats = {}

    for col in GUIDED_FEATURE_COLS:
        values = out_df[col].to_numpy(dtype=np.float32)
        feature_stats[f"{col}_mean"] = float(np.mean(values))
        feature_stats[f"{col}_std"] = float(np.std(values))
        feature_stats[f"{col}_min"] = float(np.min(values))
        feature_stats[f"{col}_max"] = float(np.max(values))

    return {
        "status": "processed",
        "video_id": video_id,
        "label": int(label),
        "label_name": label_name,
        "input_csv": str(input_csv),
        "output_csv": str(output_csv),
        "num_frames": int(len(out_df)),
        "num_raw_skeleton_features": int(len(XYZ_COLS)),
        "num_guided_features": int(len(GUIDED_FEATURE_COLS)),
        "num_total_model_features": int(len(XYZ_COLS) + len(GUIDED_FEATURE_COLS)),
        **feature_stats,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Compute Yadav2021-style guided geometric and kinematic features."
    )

    parser.add_argument(
        "--index-csv",
        type=str,
        default=str(BASELINE_ROOT / "data" / "yadav17_skeleton" / "yadav17_skeleton_index.csv"),
        help="Index CSV generated by file 02.",
    )

    parser.add_argument(
        "--output-dir",
        type=str,
        default=str(BASELINE_ROOT / "data" / "guided_features"),
        help="Output folder for skeleton + guided feature CSVs.",
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Limit number of videos for quick testing.",
    )

    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing guided feature CSV files.",
    )

    args = parser.parse_args()

    index_csv = Path(args.index_csv)
    output_dir = Path(args.output_dir)
    reports_dir = BASELINE_ROOT / "outputs" / "reports"

    ensure_dir(output_dir)
    ensure_dir(reports_dir)

    if not index_csv.exists():
        raise FileNotFoundError(f"File 02 index not found: {index_csv}")

    index_df = pd.read_csv(index_csv)

    if args.limit is not None:
        index_df = index_df.head(args.limit).copy()

    print("=" * 100)
    print("FILE 03 - Compute Yadav-style guided geometric and kinematic features")
    print("=" * 100)
    print(f"Input index:     {index_csv}")
    print(f"Output dir:      {output_dir}")
    print(f"Videos in index: {len(index_df)}")
    print(f"Limit:           {args.limit}")
    print(f"Overwrite:       {args.overwrite}")
    print("=" * 100)

    rows = []
    failed_rows = []

    for pos, (_, row) in enumerate(index_df.iterrows(), start=1):
        try:
            video_id = make_safe_name(str(row["video_id"]))
            label = int(row["label"])
            label_name = str(row["label_name"])

            input_csv = Path(str(row["output_csv"]))

            if not input_csv.exists():
                input_csv = Path(str(row["source_csv"]))

            output_csv = output_dir / label_name / f"{video_id}.csv"

            result = process_one_csv(
                input_csv=input_csv,
                output_csv=output_csv,
                video_id=video_id,
                label=label,
                label_name=label_name,
                overwrite=args.overwrite,
            )

            rows.append(result)

        except Exception as e:
            failed_rows.append({
                "video_id": str(row.get("video_id", "")),
                "input_csv": str(row.get("output_csv", "")),
                "error": repr(e),
            })

        if pos % 500 == 0 or pos == len(index_df):
            print(f"[{pos}/{len(index_df)}] processed_or_skipped={len(rows)} | failed={len(failed_rows)}")

    out_index_df = pd.DataFrame(rows)
    failed_df = pd.DataFrame(failed_rows)

    out_index_csv = output_dir / "guided_features_index.csv"
    failed_csv = output_dir / "guided_features_failed_files.csv"

    if len(out_index_df) > 0:
        out_index_df.to_csv(out_index_csv, index=False)
    else:
        pd.DataFrame().to_csv(out_index_csv, index=False)

    if len(failed_df) > 0:
        failed_df.to_csv(failed_csv, index=False)
    else:
        pd.DataFrame(columns=["video_id", "input_csv", "error"]).to_csv(failed_csv, index=False)

    success_df = out_index_df[out_index_df["status"].isin(["processed", "skipped_existing"])] if len(out_index_df) > 0 else pd.DataFrame()

    total_frames = int(success_df["num_frames"].fillna(0).sum()) if "num_frames" in success_df.columns else 0

    if len(success_df) > 0:
        label_video_counts = success_df.groupby("label_name")["video_id"].nunique().to_dict()
    else:
        label_video_counts = {}

    report = {
        "status": "completed",
        "pipeline_note": "Compute paper-style guided geometric and kinematic features from adapted Yadav17 normalized 3D skeletons.",
        "input_index_csv": str(index_csv),
        "output_dir": str(output_dir),
        "num_input_videos": int(len(index_df)),
        "num_success_or_skipped": int(len(rows)),
        "num_failed": int(len(failed_rows)),
        "total_frames_success": total_frames,
        "label_video_counts": {str(k): int(v) for k, v in label_video_counts.items()},
        "raw_skeleton_feature_columns": XYZ_COLS,
        "guided_feature_columns": GUIDED_FEATURE_COLS,
        "num_raw_skeleton_features": int(len(XYZ_COLS)),
        "num_guided_features": int(len(GUIDED_FEATURE_COLS)),
        "num_total_model_features": int(len(XYZ_COLS) + len(GUIDED_FEATURE_COLS)),
        "output_index_csv": str(out_index_csv),
        "failed_csv": str(failed_csv),
        "feature_explanation": {
            "velocity_xyz": "Frame-to-frame displacement of spine_mid joint.",
            "acceleration_xyz": "Frame-to-frame change of spine_mid velocity.",
            "floor_distance_proxy": "Absolute distance between head_y and lower-body floor proxy. This is an approximation because the estimated 3D pose has no real Kinect floor plane.",
            "body_height": "3D skeleton bounding-box height along y-axis.",
            "body_width": "3D skeleton bounding-box width along x-axis.",
            "angle_left_standing_deg": "Angle at left knee using hip-left, knee-left, ankle-left.",
            "angle_right_standing_deg": "Angle at right knee using hip-right, knee-right, ankle-right.",
            "angle_standing_deg": "Angle between head-to-spine-base body line and vertical y-axis.",
            "angle_sitting_left_deg": "Angle at left hip using spine-base, hip-left, knee-left.",
            "angle_sitting_right_deg": "Angle at right hip using spine-base, hip-right, knee-right.",
        },
    }

    report_path = reports_dir / "03_compute_guided_features_report.json"
    save_json(report, report_path)

    print("=" * 100)
    print("FILE 03 completed.")
    print("=" * 100)
    print(f"Success/skipped videos: {len(rows)}")
    print(f"Failed videos:          {len(failed_rows)}")
    print(f"Total frames:           {total_frames}")
    print(f"Label videos:           {label_video_counts}")
    print(f"Raw skeleton features:  {len(XYZ_COLS)}")
    print(f"Guided features:        {len(GUIDED_FEATURE_COLS)}")
    print(f"Total model features:   {len(XYZ_COLS) + len(GUIDED_FEATURE_COLS)}")
    print(f"Output index CSV:       {out_index_csv}")
    print(f"Failed CSV:             {failed_csv}")
    print(f"Report:                 {report_path}")
    print("=" * 100)


if __name__ == "__main__":
    main()

